# Generated by Django 5.2 on 2025-11-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=500)),
                ('course', models.CharField(choices=[('python_basic', 'Python Basic'), ('python_advanced', 'Python Advanced'), ('django_fullstack', 'Django Full-Stack')], max_length=50)),
                ('adhaarcard', models.FileField(upload_to='adhaar_cards/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
