# Generated by Django 5.2 on 2025-11-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livewire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='project_thumbnails/')),
                ('project_file', models.FileField(upload_to='student_projects/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='enroll',
            name='adhaarcard',
            field=models.FileField(blank=True, null=True, upload_to='adhaar_cards/'),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='course',
            field=models.CharField(max_length=50),
        ),
    ]
