# Generated by Django 5.2 on 2025-11-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livewire', '0002_studentproject_alter_enroll_adhaarcard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentproject',
            name='project_file',
        ),
        migrations.AddField(
            model_name='studentproject',
            name='project_url',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
